### ISSUE TITLE
Sierra Plot with POSTGRESQL Database in Grafana 9.4.7

### ISSUE THREAD

**Issue by LuRoskosch** [boazreicher/sierra-plot#3]
Hello, i would really love to use the Sierra Plot panel. We are monitoring noise-immission data in real time and the view in that panel could show the level-time relative to different frequency bands. 

The query in the Sierra Plot panel looks like this: 
SELECT
  "timestamp" AS time,
  frequency AS breakdown,
  value AS amplitude
FROM (
  SELECT "timestamp", 'LAeq' AS frequency, LAeq AS value
  FROM SensorData
  UNION ALL
  SELECT "timestamp", 'LCeq' AS frequency, LCeq AS value
  FROM SensorData
  UNION ALL
  SELECT "timestamp", 'LZeq' AS frequency, LZeq AS value
  FROM SensorData
  UNION ALL
  SELECT "timestamp", 'LZterz_6_3hz' AS frequency, LZterz_6_3hz AS value
  FROM SensorData
  -- Add more SELECT statements for other frequencies
) t
ORDER BY time, breakdown;

![image](https://user-images.githubusercontent.com/94048555/234579021-c3bc6ad6-b6c1-4252-a2f2-79641cc0d122.png)

So this returns a dataframe/table with the columns time, breakdown (string) and amplitude (number), which matches the required data from the documentation. Somehow i can not select the breakdown values as breakdown in the panel-configuration. Does someone hve a clue how to solve this?

**Comment by boazreicher** [comment]
Hi @LuRoskosch, can you try the following:
1. Add a `Convert field type` transform, and explicitly set the types of time (time), amplitude (number) and breakdown (string)
3. Add a a `Prepare time series` transform with the format `Multi-frame time series`

That should help the plugin to detect the field names correctly

![image](https://user-images.githubusercontent.com/44614829/235302690-1b7d1303-7d3a-491c-b2e7-62acbce042c4.png)

**Comment by LuRoskosch** [comment]
Thatnk you very much for the quick support! That did solve my problem. Now the panel works as expected.
